version: "3.9"

services:
  test:
    image: exercise-6
    volumes:
      - .:/app
    working_dir: /app
    command: python3 -m pytest

  run:
    image: exercise-6
    volumes:
      - .:/app
    working_dir: /app
    command: /spark/bin/spark-submit /app/main.py
